export const WEBSOCKET_PUBLIC_URL = "http://localhost:5505/"
export const WEBSOCKET_SERVER_PORT = 5505

const QUIZ_CONFIG = {
	password: "PASSWORD",
	subject: "Cincinnati IoT",
	questions: [
		{
			question: "What city is the CVG Airport named after?",
			answers: [
				"Cincinnati",
				"Covington",
				"Cleveland",
				"Crestview Hills",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
		{
			question: "Play-Doh was originally created in Cincinnati for what purpose?",
			answers: [
				"Sculpting",
				"Cleaning wallpaper",
				"Marshmallow substitute",
				"Construction",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
		{
			question: "In the 1800s, Cincinnati was commonly referred to as the \"____ of America\"",
			answers: [
				"Crown",
				"Hometown",
				"Jewel",
				"Paris",
			],
			solution: 3,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What astronaut served as a Professor of Aerospace Engineering at the University of Cincinnati from 1971 to 1979?",
			answers: [
				"Buzz Aldrin",
				"Neil Armstrong",
				"Billie Joe Armstrong",
				"Michael Collins",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What aquarium houses over one million gallons of water?",
			answers: [
				"Columbus Zoo and Aquarium",
				"Newport Aquarium",
				"Greater Cleveland Aquarium",
				"Toledo Zoo and Aquarium",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
		{
			question: "The Cincinnati Observatory, the oldest public observatory in the United States, sits on top of what appropriately named hill?",
			answers: [
				"Lookout Hill",
				"Observation Hill",
				"Outlook Hill",
				"Powerpoint Hill",
			],
			solution: 0,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What is the name for the light show that takes over Cincinnati every year?",
			answers: [
				"Light Up",
				"Illuminate",
				"Blink",
				"Radiant",
			],
			solution: 2,
			cooldown: 5,
			time: 15,
		},
		{
			question: "On April 1, 1853, Cincinnati became the first city to have a a paid...",
			answers: [
				"Parks and Recreation Department",
				"Public Works Department",
				"Police Department",
				"Fire Department",
			],
			solution: 3,
			cooldown: 5,
			time: 15,
		},
		{
			question: "In pounds, how much chili is consumed by Cincinnatians in a year?",
			answers: [
				"500,000",
				"850,000",
				"1 Million",
				"Over 2 Million",
			],
			solution: 3,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What popular card game was invented in Cincinnati?",
			answers: [
				"Apples to Apples",
				"Uno",
				"Exploding Kittens",
				"Phase 10",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What Cincinnati-based toy company made the first Star Wars figurines?",
			answers: [
				"Kenner",
				"Mattel",
				"Mego ",
				"Bandai",
			],
			solution: 0,
			cooldown: 5,
			time: 15,
		},
		{
			question: "Which university was the first in the region to offer a cybersecurity degree?",
			answers: [
				"University of Cincinnati",
				"Xavier University",
				"Northern Kentucky University",
				"Thomas More University"",
			],
			solution: 2,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What McDonalds dish was originally a Cincinnati exclusive?",
			answers: [
				"Filet-o-Fish",
				"McCrispy",
				"Sausage Burrito",
				"Sausage McMuffin",
			],
			solution: 0,
			cooldown: 5,
			time: 15,
		},
		{
			question: "The Cincinnati Zoo was the last zoo in the world to host which bird species?",
			answers: [
				"Dodo",
				"Carolina Parakeet",
				"Passenger Pigeon",
				"Stephen's Island Wren",
			],
			solution: 2,
			cooldown: 5,
			time: 15,
		},
		{
			question: "What was the first university to offer a co-op program, combining traditional education with practical work experience?",
			answers: [
				"Cincinnati State Technical and Community College",
				"Xavier University",
				"Ohio State University",
				"University of Cincinnati",
			],
			solution: 3,
			cooldown: 5,
			time: 15,
		},
		{
			question: "Kroger was the first grocer to test what modern innovation?",
			answers: [
				"Delivery",
				"Electronic scanners",
				"Subscription services",
				"Facial recognition",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
		{
			question: "Cincinnati's abandoned subway station consists of how many stations?",
			answers: [
				"7",
				"12",
				"4",
				"9",
			],
			solution: 0,
			cooldown: 5,
			time: 15,
		},
		{
			question: "TechOlympics, the nation's largest student-run tech conference, was held at what hotel until its closure in 2019?",
			answers: [
				"Cincinnatian Hotel",
				"Renaissance Hotel",
				"Millennium Hotel",
				"Century Hotel",
			],
			solution: 2,
			cooldown: 5,
			time: 15,
		},
		{
			question: "The Cincinnati Reds last won the World Series in 1990, when they swept what American League West team?",
			answers: [
				"Detroit Tigers",
				"Boston Red Sox",
				"New York Yankees",
				"Oakland Athletics",
			],
			solution: 3,
			cooldown: 5,
			time: 15,
		},
		{
			question: "How many Fortune 500 companies have their headquarters in Cincinnati?",
			answers: [
				"6",
				"7",
				"5",
				"11",
			],
			solution: 1,
			cooldown: 5,
			time: 15,
		},
	],
}

// DONT CHANGE
export const GAME_STATE_INIT = {
	started: false,
	players: [],
	playersAnswer: [],
	manager: null,
	room: null,
	currentQuestion: 0,
	roundStartTime: 0,
	...QUIZ_CONFIG,
}
